builds:
  - binary: sekret
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: binary
