language: go

go:
  - '1.10'

script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      bash <(curl -s https://codecov.io/bash)
    fi

  - |
    set -x
    if [[ -n "$TRAVIS_TAG" ]]; then
      work_dir=$(pwd)
      cd $HOME
      curl -LSfs -O \
        https://github.com/goreleaser/goreleaser/releases/download/v0.83.3/goreleaser_Linux_x86_64.tar.gz
      tar xf goreleaser_Linux_x86_64.tar.gz
      cd $work_dir
      $HOME/goreleaser
    fi

notifications:
  email: false
  slack:
    secure: Gn/04W/nhM899WESJXuFcHQd/bItg3x0ctHvNteYd1UzvaK2sXDLJx6pSZNIMvK9DfgnQK0RhPeC+BRPPpFYITYaTD+IlhDQ6MiIwc0CCedyJcb8C76URpcfG3QWXlFmW1NH6ql+Y4MnMKNtRqRvrqjVYICe7gpJXxYWRyndFDu2AE4xQpUYmvJGPmq7iOW9B3CyMBMcZui28F2A9N9sr02SNfLxH1q8tZk4Hlf7b70GOdldfJEachn/w0bBaL/XQkuPPVyXObzlYm39HRhEN7rRwAGzb/ILtJwwShYBmQEWW7Egfl1REaf0kW9RUKNVSwK9+PcD2fwxWWpYDfXOJnHLTjbn1MfheslQOhUP+kstQYTHqA5gGjwtdCfvMsqqS6UKoUfKULbIXZAWq0m7s5HbEccyzm3sJ7tDc/UdmdrvpDC2gy8Csd7HKNYzIfPVs945POwkRHlHNcKDLzDrD7Xl+0VN7LJATrsCINqj0fb4Hhy6VRe370M878xCj0NXPw3Y0IJnxFd4757BrXul2GZk4GI2Wi+qd9GAVO02db46I+s9BlO1MkMb4GdkGu3SnwzEpHU1wcY+25PPjPZqfQkPrvTxPSPN9P/JL6qasGMD5GxZ87mBfgNjYAi+IviuHWYyL++h5xngfY5cr6cTROsZpa8vdst7YyWaSqxl4qg=

env:
  global:
    secure: LF5o6umdNZq12hcqhlsmDndV5ecqvYkfgkUCO5Q+Kpl9YBIZBgYxXikY7Xx2uhK3xHuL47Uom5MbZz5NST2ExUDTMbFJ6PP8cxE5CFtXxdo/f6ZYaX3n2JAPjZwK+5CVZJ1d8ufpCnvrOMGFKSfXApB6Bla0dxRGTbLuxCF01W7HZQB9H1rzm67XDmerc1Zzg/p0hK4M2CSVweXEGQbACOvgvzvOHBcGw53w3yMh5K5OZpxW8PVVeHpVXmMzsabTprQS5F75fLfOjmRIgo1YdQbg59vrwZR4MgA9BOzGC7Wd3j4VzhYvIdzDknbUFyWPi93OMfVTIfrk/OFRCqyUmUlxJSg5H7yuOQP2s7xBGFjNhlL3huQmtvQ3EaCKnexgkYXegL1bJ5e9m75OXIoaBokw3dr2+FOdSgNUGvm/5cwBO/2Ex9oFhjQFlf4oJf61QYAWLVSjoKhHI6QsjezcBbc3MqTrvFcgbu/ONXz8HsrXtJeIGfWnaSzbrvPcZaOdYyyMDGfYOmtFSZNh82mmTBKetfrt/Tec7lFsNncZWGbthkeRTjIphFPRHdXRA5Db3nHXqWJt0ldnAocDRhuNmfgKlrHbKwqRj+ztzPpvewhlDaH212m5jjbFN8tdPcHGeI7RpjuasHodgdlS2QUtX5RQiWMAs86Dcx4wncKml/8=
